name: run reihFockle.py

on:
  schedule:
    - cron: '*/6 * * * *'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: exectute py script
        env:
          FOLLIAGHT: ${{secrets.FOLLIAGHT}}
        run: python reihFockle.py

      - name: commit files
        run: |
          git config --local user.email "peter.crellin@sch.im"
          git config --local user.name "ynskimmeegaelgagh"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs"  --allow empty)

      - name: GitHub Push   
        uses: ad-m/github-push-action@v0.8.0
          with:
            github_token: ${{secrets.FOLLIAGHT}}
            branch: main
